ic_msvcr90 DllMain conflicting types
Fixes the following error:
    scons: Reading SConscript files ...
    scons: done reading SConscript files.
    scons: Building targets ...
    gcc -o stub\ic_msvcr90.o -c stub\ic_msvcr90.c
    stub\ic_msvcr90.c:101:13: error: conflicting types for 'DllMain'
     BOOL WINAPI DllMain (HANDLE hInst,
                 ^
    In file included from c:\mingw\include\windows.h:62:0,
                     from stub\ic_msvcr90.c:41:
    c:\mingw\include\winbase.h:1051:13: note: previous declaration of 'DllMain' was here
     BOOL WINAPI DllMain(HINSTANCE, DWORD, LPVOID);
                 ^
    scons: *** [stub\ic_msvcr90.o] Error 1
    scons: building terminated because of errors.

Signed-off-by: Tim Orling <TicoTimo@gmail.com>